# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end

# Project specfic custom matchers
RSpec::Matchers.define :contain do |player_name|
  match do |collection|
    matched = false
    collection.each do |item|
      if (item.name == player_name) then
        matched = true
      end
    end
    matched
  end
end

RSpec::Matchers.define :contain_anonymous do |player_type|
  match do |collection|
    matched = false
    collection.each do |item|
      if (item.class.to_s == player_type) then
        matched = true
      end
    end
    matched
  end
end
